#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run npm install if there are changes in package.json or package-lock.json
if git diff --name-only HEAD@{1} HEAD | grep -E 'package(-lock)?\.json$'; then
    echo "📦 Dependencies changed! Running npm install..."
    npm install
fi
